spring:
  datasource:
    url: jdbc:mysql://localhost:3306/coffee_shop_9
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password:

  thymeleaf:
    cache: false

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true